services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.2'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8080}:80'
            - '${VITE_PORT:-5174}:5173'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            DB_CONNECTION: '${DB_CONNECTION:-sqlite}'
            DB_DATABASE: '${DB_DATABASE:-database/database.sqlite}'
            QUEUE_CONNECTION: '${QUEUE_CONNECTION:-database}'
            CACHE_STORE: '${CACHE_STORE:-database}'
            SESSION_DRIVER: '${SESSION_DRIVER:-database}'
        volumes:
            - '.:/var/www/html'
            - './database/database.sqlite:/var/www/html/database/database.sqlite'
        networks:
            - sail
        depends_on:
            - node
        healthcheck:
            test:
                - CMD
                - curl
                - -f
                - http://localhost/health
            retries: 3
            timeout: 5s

    node:
        image: 'node:18-alpine'
        ports:
            - '${NODE_PORT:-3000}:3000'
        environment:
            NODE_ENV: '${NODE_ENV:-development}'
        volumes:
            - '.:/app'
            - '/app/node_modules'
        working_dir: /app
        networks:
            - sail
        command: sh -c "npm install && npm run dev"
        healthcheck:
            test:
                - CMD
                - curl
                - -f
                - http://localhost:3000
            retries: 3
            timeout: 5s

    queue:
        build:
            context: './vendor/laravel/sail/runtimes/8.2'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.2/app'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            DB_CONNECTION: '${DB_CONNECTION:-sqlite}'
            DB_DATABASE: '${DB_DATABASE:-database/database.sqlite}'
            QUEUE_CONNECTION: '${QUEUE_CONNECTION:-database}'
            CACHE_STORE: '${CACHE_STORE:-database}'
        volumes:
            - '.:/var/www/html'
            - './database/database.sqlite:/var/www/html/database/database.sqlite'
        networks:
            - sail
        depends_on:
            - laravel.test
        command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600

    redis:
        image: redis:7-alpine
        ports:
            - "6380:6379"
        volumes:
            - redis-data:/data

networks:
    sail:
        driver: bridge

volumes:
    redis-data:
